### ISSUE TITLE
session cookie storage

### ISSUE THREAD

**Issue by salt-die** [Starwort/aoc_helper#1]
I store this in aoc_helper directory in my project and have .token added to .gitignore, but maybe we should just look in some default user directory (~/ or wherever) for the session cookie.  Or require some global variable set.

Need to put directions for getting cookie in the README

**Comment by Starwort** [comment]
Yup, I'm looking at AOCD for the path reading code (some kind of os.expand IIRC), and the cookie fetching should be moderately easy to write up. For now, my priority is getting the library working, then adding documentation

**Comment by Starwort** [comment]
aoc_helper is now able to store token in `~/.config/aoc_helper/token.txt`. On first use, the user is prompted for their token, which will be saved. Documentation still needed

**Comment by salt-die** [comment]
entering session cookie through stdin seems like a pain, i might just error, but maybe it's fine

**Comment by Starwort** [comment]
It's a one-time thing so I don't see how it would be too bad
