### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by dreua** [Starwort/aoc_helper#11]
How do you feel about switching to "main" as the default branch name? Many projects (including Github and Fedora) have done this switch and I personally think it's a good idea.

[github/renaming: Guidance for changing the default branch name for GitHub repositories](https://github.com/github/renaming)

**Comment by Starwort** [comment]
[This medium article](https://mooseyanon.medium.com/github-f-ck-your-name-change-de599033bbbe) is a fairly good expression of my thoughts on the matter.

Essentially, the term 'master' (as in 'master copy', referring to an original or authoritative copy of a document) is a perfectly reasonable branch name, and I see no reason to move away from it.
