### ISSUE TITLE
User position

### ISSUE THREAD

**Issue by Starwort** [Starwort/aoc_helper#2]
In the comments for submit, we debated whether to print the user's position; do we want to explicitly print the user's position (in which case we can fetch it from `leaderboard/self`, rather than just printing every output)?

**Comment by salt-die** [comment]
I dunno, It's not super important.  I sort of like the responses but my opinions aren't strong.

**Comment by Starwort** [comment]
I feel like we could just provide our own output if we want to provide that behaviour, then we also get more control over the formatting and content - especially the `[share to]` message is a little odd when we're parsing text only
